name: Deploy

on:
  push:
    branches: [deploy]

jobs:
  initialize:
    runs-on: [self-hosted, builder]

    steps:
      - uses: actions/checkout@v4
        name: Checkout code

      - uses: .github/actions/notify
        name: Notify workflow started
        with:
          status: started
          phase: Deploy

  build:
    runs-on: [self-hosted, builder]
    needs: initialize

    env:
      COREPACK_ENABLE_STRICT: '0'

    steps:
      - uses: actions/checkout@v4
        name: Checkout code

      - run: corepack enable
        name: Enable pnpm

      - run: pnpm install --frozen-lockfile
        name: Install dependencies

      - run: pnpm check
        name: Type-check, lint, and format

      - run: pnpm test
        name: Run tests

      - run: pnpm build
        name: Build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_IMAGE }}:${{ github.sha }}
            ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_IMAGE }}:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_IMAGE }}:buildcache,mode=max

      - uses: .github/actions/notify
        name: Notify build result
        with:
          status: ${{ job.status }}
          phase: Build

  deploy:
    runs-on: [self-hosted, deployer]

    needs: build

    steps:
      - uses: actions/checkout@v4
        name: Checkout code

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Set up KubeConfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig

      - id: commit
        shell: bash
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B | tr -d '\n' | cut -c1-240)
          echo "COMMIT_MSG=$COMMIT_MSG" >> $GITHUB_ENV

      - shell: bash
        run: |
          for file in ./k8s/*.yaml; do
            sed \
              -e "s|\${IMAGE}|${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_IMAGE }}:${{ github.sha }}|g" \
              -e "s|\${NAMESPACE}|${{ secrets.K8S_NAMESPACE }}|g" \
              -e "s|\${SERVICE-NAME}|${{ secrets.K8S_SERVICE_NAME }}|g" \
              -e "s|\${DB_CONNECTION}|${{ secrets.DATABASE_URI }}|g" \
              -e "s|\${VERSION}|${{ github.sha }}|g" \
              -e "s|\${COMMAND}|start|g" \
              -e "s|\${INSTANCE}|1|g" \
              -i "$file"
          done

      - shell: bash
        run: |
          kubectl --kubeconfig=kubeconfig apply -f ./k8s/
          kubectl --kubeconfig=kubeconfig rollout restart deployment ${{ secrets.K8S_SERVICE_NAME }} -n ${{ secrets.K8S_NAMESPACE }}
          kubectl --kubeconfig=kubeconfig annotate deployment ${{ secrets.K8S_SERVICE_NAME }} git-commit-message="${{ env.COMMIT_MSG }}" -n ${{ secrets.K8S_NAMESPACE }} --overwrite

      - uses: .github/actions/notify
        name: Notify deploy result
        with:
          status: ${{ job.status }}
          phase: Deploy
